name: Deploy Jekyll Site to GitHub Pages

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '.github/**' # Ignore changes towards the .github directory
    branches:
    - main # Only trigger on the main branch
          
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        publish_branch: gh-pages
        force_orphan: true # This creates the branch if it doesn't exist
        keep_files: false # This will remove files that are not in the publish_dir
        commit_message: "Deploying Site" # This is the commit message for the deployment
        allow_empty_commit: false # This will allow the deployment to be committed even if there are no changes
