name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # replace with your default branch name if not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy _site to another branch
        run: |
          git fetch
          git checkout github_pages || git checkout -b github_pages
          git rm -rf ./*
          git checkout main -- _site
          mv _site/* .
          git add .
          git commit -m "Update _site folder" || echo "No changes to commit"
          git push origin github_pages || echo "No changes to push"
