name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # replace with your default branch name if not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy _site to another branch
        run: |
          git checkout github_pages
          git checkout main -- _site
          git commit -m "Update _site folder"
          git push origin github_pages
